version: '2'
services:

  front-react:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      NODE_ENV: development
    depends_on:
      - server-dev
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "5000:5000"
      - "9009:9009"

  server-dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db-dev
      - mongodb-dev
    volumes:
      - ./data/dev/images:/var/www/html/images
      - ./server:/server
      - /server/node_modules

  db-dev:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - ./data/dev:/var/lib/postgresql/data

  mongodb-dev:
    image: mongo:latest
    restart: always

    ports:
      - "27018:27018"
    volumes:
      - ./data/dev:/data/db
      - ./data/dev/configdb:/data/configdb

