version: '2'
services:

  nginx-server-prod:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - "80:80"
    depends_on:
      - server-prod
    volumes:
      - ./data/prod/images:/var/www/html/images:ro

  server-prod:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 8081
    restart: always
    depends_on:
      - db-prod
      - mongodb-prod
    volumes:
      - ./data/prod/images:/var/www/html/images

  db-prod:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo-prod
    volumes:
      - ./data/prod:/var/lib/postgresql/data

  mongodb-prod:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=chat-prod
    volumes:
      - ./data/prod/db:/data/db
      - ./data/prod/configdb:/data/configdb

