const CHAT_ACTION_TYPES = {

    SELECT_CHAT_ROOM_ACTION: "SELECT_CHAT_ROOM_ACTION",

    GET_USER_CHATS_ACTION: "GET_USER_CHATS_ACTION",
    GET_USER_CHATS_REQUEST: "GET_USER_CHATS_REQUEST",
    GET_USER_CHATS_RESPONSE: "GET_USER_CHATS_RESPONSE",
    GET_USER_CHATS_ERROR: "GET_USER_CHATS_ERROR",

    GET_CHAT_MESSAGES_ACTION: "GET_CHAT_MESSAGES_ACTION",
    GET_CHAT_MESSAGES_REQUEST: "GET_CHAT_MESSAGES_REQUEST",
    GET_CHAT_MESSAGES_RESPONSE: "GET_CHAT_MESSAGES_RESPONSE",
    GET_CHAT_MESSAGES_ERROR: "GET_CHAT_MESSAGES_ERROR",

    MESSAGE_RECEIVED_ACTION: "MESSAGE_RECEIVED_ACTION",
    NOTIFY_TYPING_ACTION: "NOTIFY_TYPING_ACTION",
    NOTIFY_TYPING_STOP_ACTION: "NOTIFY_TYPING_STOP_ACTION",

    SEND_MESSAGE_ACTION: 'SEND_MESSAGE_ACTION',
    SEND_MESSAGE_ERROR: 'SEND_MESSAGE_ERROR',

    CLOSE_OPEN_CHAT_MENU_ACTION: 'CLOSE_OPEN_CHAT_MENU_ACTION',

};

export default CHAT_ACTION_TYPES;

