const CHAT_ACTION_TYPES = {

    CREATE_CHAT_ACTION: 'CREATE_CHAT_ACTION',
    SELECT_CHAT_ACTION: "SELECT_CHAT_ACTION",
    
    CREATE_CHAT_REQUEST: 'CREATE_CHAT_REQUEST',
    CREATE_CHAT_RESPONSE: 'CREATE_CHAT_RESPONSE',
    CREATE_CHAT_ERROR: 'CREATE_CHAT_ERROR',

    /*
    * CHAT
    * */
    GET_USER_CHATS_ACTION: "GET_USER_CHATS_ACTION",
    GET_CHATS_REQUEST: "GET_CHATS_REQUEST",
    GET_CHATS_RESPONSE: "GET_CHATS_RESPONSE",
    GET_CHATS_ERROR: "GET_CHATS_ERROR",

    GET_CHAT_ACTION: "GET_CHAT_ACTION",
    GET_CHAT_REQUEST: "GET_CHAT_REQUEST",
    GET_CHAT_RESPONSE: "GET_CHAT_RESPONSE",
    GET_CHAT_ERROR: "GET_CHAT_ERROR",
    
    /*
    * MESSAGE
    * */
    GET_MESSAGES_ACTION: "GET_MESSAGES_ACTION",
    GET_MESSAGES_REQUEST: "GET_MESSAGES_REQUEST",
    GET_MESSAGES_RESPONSE: "GET_MESSAGES_RESPONSE",
    GET_MESSAGES_ERROR: "GET_MESSAGES_ERROR",

    GET_MESSAGE_ACTION: "GET_MESSAGE_ACTION",
    GET_MESSAGE_REQUEST: "GET_MESSAGE_REQUEST",
    GET_MESSAGE_RESPONSE: "GET_MESSAGE_RESPONSE",
    GET_MESSAGE_ERROR: "GET_MESSAGE_ERROR",
    
    /*
    * PARTICIPANTS
    * */
    GET_PARTICIPANTS_ACTION: 'GET_PARTICIPANTS_ACTION',
    GET_PARTICIPANTS_REQUEST: 'GET_PARTICIPANTS_REQUEST',
    GET_PARTICIPANTS_RESPONSE: 'GET_PARTICIPANTS_RESPONSE',
    GET_PARTICIPANTS_ERROR: 'GET_PARTICIPANTS_ERROR',

    
    MESSAGE_RECEIVED_ACTION: "MESSAGE_RECEIVED_ACTION",
    NOTIFY_TYPING_ACTION: "NOTIFY_TYPING_ACTION",
    NOTIFY_TYPING_STOP_ACTION: "NOTIFY_TYPING_STOP_ACTION",

    SEND_MESSAGE_ACTION: 'SEND_MESSAGE_ACTION',
    SEND_MESSAGE_ERROR: 'SEND_MESSAGE_ERROR',

    CLOSE_OPEN_CHAT_MENU_ACTION: 'CLOSE_OPEN_CHAT_MENU_ACTION',
    
    CANCEL_SEARCH_CHAT_ROOM_ACTION: 'CANCEL_SEARCH_CHAT_ROOM_ACTION',
    
    
    
    
};

export default CHAT_ACTION_TYPES;

