const CONTEST_ACTION_TYPES = {

    SET_PAGINATION_LIMIT: 'SET_PAGINATION_LIMIT',
    SET_PAGINATION_OFFSET: 'SET_PAGINATION_OFFSET',
    PAGINATION_OFFSET_INCREMENT: 'PAGINATION_OFFSET_INCREMENT',
    PAGINATION_OFFSET_DECREMENT: 'PAGINATION_OFFSET_DECREMENT',
    PAGINATION_RESET: 'PAGINATION_RESET',

    ADD_FILTER_PROPS: 'ADD_FILTER_PROPS',
    REMOVE_FILTER_PROPS: 'REMOVE_FILTER_PROPS',
    CHANGE_FILTER_PROPS: 'CHANGE_FILTER_PROPS',
    SET_FILTER: 'SET_FILTER',
    RESET_FILTER_ACTION: 'RESET_FILTER_ACTION',
    SELECT_CONTEST_ACTION: 'SELECT_CONTEST_ACTION',


    LIKE_CONTEST_ACTION: 'LIKE_CONTEST_ACTION',
    LIKE_CONTEST_REQUEST: 'LIKE_CONTEST_REQUEST',
    LIKE_CONTEST_RESPONSE: 'LIKE_CONTEST_RESPONSE',
    LIKE_CONTEST_ERROR: 'LIKE_CONTEST_ERROR',

    UPDATE_CONTEST_RESPONSE: 'UPDATE_CONTEST_RESPONSE',

    DISLIKE_CONTEST_ACTION: 'DISLIKE_CONTEST_ACTION',
    DISLIKE_CONTEST_REQUEST: 'DISLIKE_CONTEST_REQUEST',
    DISLIKE_CONTEST_RESPONSE: 'DISLIKE_CONTEST_RESPONSE',
    DISLIKE_CONTEST_ERROR: 'DISLIKE_CONTEST_ERROR',
    CREATE_TASK_CHAT_RESPONSE: 'CREATE_TASK_CHAT_RESPONSE',
};

export default CONTEST_ACTION_TYPES;
