const CONTEST_ACTION_TYPES = {

    SET_PAGINATION_LIMIT: 'SET_PAGINATION_LIMIT',
    SET_PAGINATION_OFFSET: 'SET_PAGINATION_OFFSET',
    PAGINATION_OFFSET_INCREMENT: 'PAGINATION_OFFSET_INCREMENT',
    PAGINATION_OFFSET_DECREMENT: 'PAGINATION_OFFSET_DECREMENT',
    PAGINATION_RESET: 'PAGINATION_RESET',

    ADD_FILTER_PROPS: 'ADD_FILTER_PROPS',
    REMOVE_FILTER_PROPS: 'REMOVE_FILTER_PROPS',
    SET_FILTER: 'SET_FILTER',

    SELECT_CONTEST_ACTION: 'SELECT_CONTEST_ACTION',

};

export default CONTEST_ACTION_TYPES;
