const ENTRY_ACTION_TYPES = {
    
    GET_ENTRIES_ACTION: 'GET_ENTRIES_ACTION',
    GET_ENTRIES_REQUEST: 'GET_ENTRIES_REQUEST',
    GET_ENTRIES_RESPONSE: 'GET_ENTRIES_RESPONSE',
    GET_ENTRIES_ERROR: 'GET_ENTRIES_ERROR',

    POST_ENTRY_ACTION: 'POST_ENTRY_ACTION',
    POST_ENTRY_REQUEST: 'POST_ENTRY_REQUEST',
    POST_ENTRY_RESPONSE: 'POST_ENTRY_RESPONSE',
    POST_ENTRY_ERROR: 'POST_ENTRY_ERROR',

    REJECT_ENTRY_ACTION: 'REJECT_ENTRY_ACTION',
    REJECT_ENTRY_REQUEST: 'REJECT_ENTRY_REQUEST',
    REJECT_ENTRY_RESPONSE: 'REJECT_ENTRY_RESPONSE',
    REJECT_ENTRY_ERROR: 'REJECT_ENTRY_ERROR',

    SET_WINNING_ENTRY_ACTION: 'SET_WINNING_ENTRY_ACTION',
    SET_WINNING_ENTRY_REQUEST: 'SET_WINNING_ENTRY_REQUEST',
    SET_WINNING_ENTRY_RESPONSE: 'SET_WINNING_ENTRY_RESPONSE',
    SET_WINNING_ENTRY_ERROR: 'SET_WINNING_ENTRY_ERROR',


};


export default ENTRY_ACTION_TYPES;
