const ACTION_TYPES = {
    /*
    * NAVIGATION ACTIONS
    * */
    GET_ADMIN_NAVIGATION: "GET_ADMIN_NAVIGATION",
    GET_BUYER_NAVIGATION: "GET_BUYER_NAVIGATION",
    GET_CREATIVE_NAVIGATION: "GET_CREATIVE_NAVIGATION",
    GET_GUEST_NAVIGATION: "GET_GUEST_NAVIGATION",
    /*
    * contest
    * */
    SET_SELECTED_TASK_TYPES: "SET_SELECTED_TASK_TYPES",
    REMOVE_SELECTED_TASK_TYPES: "REMOVE_SELECTED_TASK_TYPES",

    /*
    * Authorization page mode
    * */
    CHANGE_AUTHORIZATION_MODE_ACTION: 'CHANGE_AUTHORIZATION_MODE_ACTION',
    AUTHORIZATION_SIGN_UP_MODE_ACTION: "AUTHORIZATION_SIGN_UP_MODE_ACTION",
    AUTHORIZATION_LOGIN_MODE_ACTION: "AUTHORIZATION_LOGIN_MODE_ACTION",
    AUTHORIZATION_COVER_ERROR: "AUTHORIZATION_COVER_ERROR",
    /*
    * LOGIN AND SIGN_UP GET THE SAME STATE (USER,TOKEN_PAIR)
    * */
    USER_LOGIN_ACTION: 'USER_LOGIN_ACTION',
    USER_SIGN_UP_ACTION: 'USER_SIGN_UP_ACTION',

    GET_AUTHORIZED_USER: "GET_AUTHORIZED_USER",

    AUTHORIZATION_LOGOUT_ACTION: 'AUTHORIZATION_LOGOUT_ACTION',


    USER_AUTHORIZATION_REQUEST: 'USER_AUTHORIZATION_REQUEST',
    USER_AUTHORIZATION_RESPONSE: 'USER_AUTHORIZATION_RESPONSE',
    USER_AUTHORIZATION_ERROR: 'USER_AUTHORIZATION_ERROR',


    /*
    * USERs ACTIONS
    * */
    GET_USERS_ACTION: 'GET_USERS_ACTION',
    GET_USERS_REQUEST: 'GET_USERS_REQUEST',
    GET_USERS_RESPONSE: 'GET_USERS_RESPONSE',
    GET_USERS_ERROR: 'GET_USERS_ERROR',
    GET_USERS_LIMIT_CHANGE: 'GET_USERS_ERROR',

    SET_USERS_QUERY_STRING_ACTION: "SET_USERS_QUERY_STRING_ACTION",

    /*
    * USER ACTIONS
    * */
    //CREATE
    CREATE_USER_ACTION: 'CREATE_USER_ACTION',

    CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
    CREATE_USER_RESPONSE: 'CREATE_USER_RESPONSE',
    CREATE_USER_ERROR: 'CREATE_USER_ERROR',

    //READ
    GET_USER_ACTION: 'GET_USER_ACTION',

    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_RESPONSE: 'GET_USER_RESPONSE',
    GET_USER_ERROR: 'GET_USER_ERROR',

    //UPDATE
    UPDATE_USER_ACTION: 'UPDATE_USER_ACTION',

    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_RESPONSE: 'UPDATE_USER_RESPONSE',
    UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',

    //DELETE
    DELETE_USER_ACTION: 'DELETE_USER_ACTION',

    DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
    DELETE_USER_RESPONSE: 'DELETE_USER_RESPONSE',
    DELETE_USER_ERROR: 'DELETE_USER_ERROR',


    /*
    * CONTESTS
    * */
    CREATE_CONTEST_ACTION: 'CREATE_CONTEST_ACTION',
    CREATE_CONTEST_REQUEST: 'CREATE_CONTEST_REQUEST',
    CREATE_CONTEST_RESPONSE: 'CREATE_CONTEST_RESPONSE',
    CREATE_CONTEST_ERROR: 'CREATE_CONTEST_ERROR',


    SET_CREATE_CONTEST_STEPS_ACTION: "SET_CREATE_CONTEST_STEPS_ACTION",
    NEXT_CREATE_CONTEST_STEP_ACTION: "NEXT_CREATE_CONTEST_ACTION",
    PREV_CREATE_CONTEST_STEP_ACTION: "PREV_CREATE_CONTEST_ACTION",
    INSERT_CONTEST_STEP_ACTION: "INSERT_CONTEST_STEP_ACTION",
    SET_CURRENT_STEP_ACTION: "SET_CURRENT_STEP_ACTION",
    DONE_CURRENT_STEP_ACTION: "DONE_CURRENT_STEP_ACTION",
    /*
        DONE_CURRENT_STEP_ACTION: "DONE_CURRENT_STEP_ACTION",
    */

    GET_ALL_CONTESTS_ACTION: 'GET_ALL_CONTESTS_ACTION',
    GET_ALL_CONTESTS_REQUEST: 'GET_ALL_CONTESTS_REQUEST',
    GET_ALL_CONTESTS_RESPONSE: 'GET_ALL_CONTESTS_RESPONSE',
    GET_ALL_CONTESTS_ERROR: 'GET_ALL_CONTESTS_ERROR',

    GET_ALL_USER_CONTESTS_ACTION: 'GET_ALL_USER_CONTESTS_ACTION',
    GET_ALL_USER_CONTESTS_REQUEST: 'GET_ALL_USER_CONTESTS_REQUEST',
    GET_ALL_USER_CONTESTS_RESPONSE: 'GET_ALL_USER_CONTESTS_RESPONSE',
    GET_ALL_USER_CONTESTS_ERROR: 'GET_ALL_USER_CONTESTS_ERROR',

    GET_CONTEST_ACTION: 'GET_CONTEST_ACTION',
    GET_CONTEST_REQUEST: 'GET_CONTEST_REQUEST',
    GET_CONTEST_RESPONSE: 'GET_CONTEST_RESPONSE',
    GET_CONTEST_ERROR: 'GET_CONTEST_ERROR',

    UPDATE_CONTEST_ACTION: 'UPDATE_CONTEST_ACTION',
    UPDATE_CONTEST_REQUEST: 'UPDATE_CONTEST_REQUEST',
    UPDATE_CONTEST_RESPONSE: 'UPDATE_CONTEST_RESPONSE',
    UPDATE_CONTEST_ERROR: 'UPDATE_CONTEST_ERROR',

    DELETE_CONTEST_ACTION: 'DELETE_CONTEST_ACTION',
    DELETE_CONTEST_REQUEST: 'DELETE_CONTEST_REQUEST',
    DELETE_CONTEST_RESPONSE: 'DELETE_CONTEST_RESPONSE',
    DELETE_CONTEST_ERROR: 'DELETE_CONTEST_ERROR',

    /*
    * TASKS
    * */
    CREATE_TASK_ACTION: 'CREATE_TASK_ACTION',
    CREATE_TASK_REQUEST: 'CREATE_TASK_REQUEST',
    CREATE_TASK_RESPONSE: 'CREATE_TASK_RESPONSE',
    CREATE_TASK_ERROR: 'CREATE_TASK_ERROR',
    UPDATE_TASK_ACTION: 'UPDATE_TASK_ACTION',
    UPDATE_TASK_REQUEST: 'UPDATE_TASK_REQUEST',
    UPDATE_TASK_RESPONSE: 'UPDATE_TASK_RESPONSE',
    UPDATE_TASK_ERROR: 'UPDATE_TASK_ERROR',
    /*
  * PAYMENT
  * */
    CONTEST_PAYMENT_ACTION: 'CONTEST_PAYMENT_ACTION',
    CONTEST_PAYMENT_REQUEST: 'CONTEST_PAYMENT_REQUEST',
    CONTEST_PAYMENT_RESPONSE: 'CONTEST_PAYMENT_RESPONSE',
    CONTEST_PAYMENT_ERROR: 'CONTEST_PAYMENT_ERROR',

    /*
     * ENTRIES
     * */
    CREATE_ENTRY_ACTION: 'CREATE_ENTRY_ACTION',
    CREATE_ENTRY_REQUEST: 'CREATE_ENTRY_REQUEST',
    CREATE_ENTRY_RESPONSE: 'CREATE_ENTRY_RESPONSE',
    CREATE_ENTRY_ERROR: 'CREATE_ENTRY_ERROR',

    GET_ENTRY_ACTION: 'GET_ENTRY_ACTION',
    GET_ENTRY_REQUEST: 'GET_ENTRY_REQUEST',
    GET_ENTRY_RESPONSE: 'GET_ENTRY_RESPONSE',
    GET_ENTRY_ERROR: 'GET_ENTRY_ERROR',


    GET_ALL_ENTRIES_ACTION: 'GET_ALL_ENTRIES_ACTION',
    GET_ALL_ENTRIES_REQUEST: 'GET_ALL_ENTRIES_REQUEST',
    GET_ALL_ENTRIES_RESPONSE: 'GET_ALL_ENTRIES_RESPONSE',
    GET_ALL_ENTRIES_ERROR: 'GET_ALL_ENTRIES_ERROR',

    UPDATE_ENTRY_ACTION: 'UPDATE_ENTRY_ACTION',
    UPDATE_ENTRY_REQUEST: 'UPDATE_ENTRY_REQUEST',
    UPDATE_ENTRY_RESPONSE: 'UPDATE_ENTRY_RESPONSE',
    UPDATE_ENTRY_ERROR: 'UPDATE_ENTRY_ERROR',

    DELETE_ENTRY_ACTION: 'DELETE_ENTRY_ACTION',
    DELETE_ENTRY_REQUEST: 'DELETE_ENTRY_REQUEST',
    DELETE_ENTRY_RESPONSE: 'DELETE_ENTRY_RESPONSE',
    DELETE_ENTRY_ERROR: 'DELETE_ENTRY_ERROR',

    /*
    * HEADER USER ITEM ACTION
    * */
    HEADER_USER_ITEM_OPEN_CLOSE_MENU_ACTION: "HEADER_USER_ITEM_OPEN_CLOSE_MENU_ACTION",

};

export default ACTION_TYPES;
