export default {
    GOODS_ACTION: 'GOODS_ACTION',
    GOODS_RESPONSE: 'GOODS_RESPONSE',
    GOODS_REQUEST: 'GOODS_REQUEST',
    GOODS_ERROR: 'GOODS_ERROR',

    SINGLE_GOODS_ACTION: 'SINGLE_GOODS_ACTION',
    SINGLE_GOODS_RESPONSE: 'SINGLE_GOODS_RESPONSE',
    UPDATE_SINGLE_GOODS_ACTION: 'UPDATE_SINGLE_GOODS_ACTION',

    /*
    * login and sign_up get the same state (user,tokenPair)
    * */
    USER_LOGIN_ACTION: 'USER_LOGIN_ACTION',
    USER_SIGN_UP_ACTION: 'USER_SIGN_UP_ACTION',
    USER_AUTHORIZATION_REQUEST: 'USER_AUTHORIZATION_REQUEST',
    USER_AUTHORIZATION_RESPONSE: 'USER_AUTHORIZATION_RESPONSE',
    USER_AUTHORIZATION_ERROR: 'USER_AUTHORIZATION_ERROR',

    /*
    * Refresh token pair*/
    REFRESH_TOKEN_PAIR_ACTION: "REFRESH_TOKEN_PAIR_ACTION",
    REFRESH_TOKEN_PAIR_REQUEST: "REFRESH_TOKEN_PAIR_REQUEST",
    REFRESH_TOKEN_PAIR_RESPONSE: "REFRESH_TOKEN_PAIR_REQUEST",
    REFRESH_TOKEN_PAIR_ERROR: "REFRESH_TOKEN_PAIR_REQUEST",

};
