export default {
    /*
    GOODS_ACTION: 'GOODS_ACTION',
    GOODS_RESPONSE: 'GOODS_RESPONSE',
    GOODS_REQUEST: 'GOODS_REQUEST',
    GOODS_ERROR: 'GOODS_ERROR',

    SINGLE_GOODS_ACTION: 'SINGLE_GOODS_ACTION',
    SINGLE_GOODS_RESPONSE: 'SINGLE_GOODS_RESPONSE',
    UPDATE_SINGLE_GOODS_ACTION: 'UPDATE_SINGLE_GOODS_ACTION',
  */

    /*
    * login and sign_up get the same state (user,tokenPair)
    * */
    USER_LOGIN_ACTION: 'USER_LOGIN_ACTION',
    USER_SIGN_UP_ACTION: 'USER_SIGN_UP_ACTION',
    USER_ACCESS_REQUEST: 'USER_ACCESS_REQUEST',
    USER_ACCESS_RESPONSE: 'USER_ACCESS_RESPONSE',
    USER_ACCESS_ERROR: 'USER_ACCESS_ERROR',

};
